apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-acecmn-mongodb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes
